services:
  - name: rabbitmq
    type: web_service
    plan: free
    dockerfilePath: ./backend/dockerfile.rabbitmq
    env:
      - key: RABBITMQ_DEFAULT_USER
        value: guest
      - key: RABBITMQ_DEFAULT_PASS
        value: guest
    healthCheckPath: /
    healthCheckTimeout: 60

  - name: redis
    type: web_service
    plan: free
    dockerfilePath: ./backend/dockerfile.redis
    healthCheckPath: /PING
    healthCheckTimeout: 30

  - name: api-proxypoint
    type: web_service
    plan: starter
    dockerfilePath: ./backend/api-proxypoint/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health

  - name: identity-service
    type: web_service
    plan: starter
    dockerfilePath: ./backend/identity-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: media-service
    type: web_service
    plan: starter
    dockerfilePath: ./backend/media-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: post-service
    type: web_service
    plan: starter
    dockerfilePath: ./backend/post-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: search-service
    type: web_service
    plan: starter
    dockerfilePath: ./backend/search-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start
