services:
  - name: redis
    type: web
    plan: free
    runtime: docker
    image:
      name: redis:alpine  # Corrected image format
    healthCheckPath: /PING
    healthCheckTimeoutSeconds: 30  # Corrected field name
    # internal: true  # Removed, field not found

  - name: rabbitmq
    type: web
    plan: free
    runtime: docker
    image:
      name: rabbitmq:3-management  # Corrected image format
    env:  # Corrected env format to be a map
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthCheckPath: /
    healthCheckTimeoutSeconds: 60  # Corrected field name
    # internal: true  # Removed, field not found

  - name: api-proxypoint
    type: web
    plan: starter
    dockerfilePath: ./backend/api-proxypoint/Dockerfile
    env:  # Corrected env format to be a map
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    buildCommand: npm install && npm run build
    startCommand: npm start

  - name: identity-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/identity-service/Dockerfile
    env:  # Corrected env format to be a map
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: media-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/media-service/Dockerfile
    env:  # Corrected env format to be a map
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: post-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/post-service/Dockerfile
    env:  # Corrected env format to be a map
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: search-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/search-service/Dockerfile
    env:  # Corrected env format to be a map
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start