services:
  - name: redis
    type: web
    plan: free
    runtime: docker
    image:
      repository: redis:alpine  # Revised image object structure
    healthCheck:  # Grouped health check parameters
      path: /PING
      timeoutSeconds: 30
    # internal: true # Removed in previous fix, still assumed correct

  - name: rabbitmq
    type: web
    plan: free
    runtime: docker
    image:
      repository: rabbitmq:3-management  # Revised image object structure
    env:  # Revised env format to list of key-value objects
      - key: RABBITMQ_DEFAULT_USER
        value: guest
      - key: RABBITMQ_DEFAULT_PASS
        value: guest
    healthCheck:  # Grouped health check parameters
      path: /
      timeoutSeconds: 60
    # internal: true # Removed in previous fix, still assumed correct

  - name: api-proxypoint
    type: web
    plan: starter
    dockerfilePath: ./backend/api-proxypoint/Dockerfile
    env:  # Revised env format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install && npm run build
    startCommand: npm start

  - name: identity-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/identity-service/Dockerfile
    env:  # Revised env format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: media-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/media-service/Dockerfile
    env:  # Revised env format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: post-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/post-service/Dockerfile
    env:  # Revised env format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: search-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/search-service/Dockerfile
    env:  # Revised env format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start