services:
  - name: redis
    type: web
    plan: free
    runtime: docker
    image:
      url: redis:alpine # Corrected image format
    healthCheckPath: /PING # Top-level field
    healthCheckTimeoutSeconds: 30 # Top-level field per Render spec
    # internal: true # Removed in previous fix

  - name: rabbitmq
    type: web
    plan: free
    runtime: docker
    image:
      url: rabbitmq:3-management # Corrected image format
    envVars: # Corrected top-level key and format
      - key: RABBITMQ_DEFAULT_USER
        value: guest
      - key: RABBITMQ_DEFAULT_PASS
        value: guest
    healthCheckPath: / # Top-level field
    healthCheckTimeoutSeconds: 60 # Top-level field per Render spec
    # internal: true # Removed in previous fix

  - name: api-proxypoint
    type: web
    plan: starter
    dockerfilePath: ./backend/api-proxypoint/Dockerfile
    envVars: # Corrected top-level key and format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install && npm run build
    startCommand: npm start

  - name: identity-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/identity-service/Dockerfile
    envVars: # Corrected top-level key and format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: media-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/media-service/Dockerfile
    envVars: # Corrected top-level key and format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: post-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/post-service/Dockerfile
    envVars: # Corrected top-level key and format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: search-service
    type: worker
    plan: starter
    dockerfilePath: ./backend/search-service/Dockerfile
    envVars: # Corrected top-level key and format
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start