# render.yaml
services:
  - name: rabbitmq
    type: docker
    plan: free
    dockerfilePath: ./Dockerfile.rabbitmq
    env:
      - key: RABBITMQ_DEFAULT_USER
        value: guest
      - key: RABBITMQ_DEFAULT_PASS
        value: guest
    healthCheckPath: "/"
    healthCheckTimeout: 60

  - name: redis
    type: docker
    plan: free
    dockerfilePath: ./Dockerfile.redis
    healthCheckPath: "/PING"
    healthCheckTimeout: 30

  - name: api-proxypoint
    type: web_service
    plan: starter
    dockerfilePath: ./api-proxypoint/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health

  - name: identity-service
    type: background_worker
    plan: starter
    dockerfilePath: ./identity-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: media-service
    type: background_worker
    plan: starter
    dockerfilePath: ./media-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: post-service
    type: background_worker
    plan: starter
    dockerfilePath: ./post-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start

  - name: search-service
    type: background_worker
    plan: starter
    dockerfilePath: ./search-service/Dockerfile
    env:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
    buildCommand: npm install
    startCommand: npm start
